### ISSUE TITLE
Use console address cause image change to xl.meta

### ISSUE THREAD

**Issue by conduongtong** [minio/minio-js#1054]
Hello,
Currently i'm using docker to run minio
```
  minio:
    image: minio/minio:RELEASE.2022-06-11T19-55-32Z
    command: server /data --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: 
      MINIO_ROOT_PASSWORD: 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always
    container_name: minio
    volumes:
      - ./minio/data:/data:rw

  minio-nginx:
    image: nginx:1.19.2-alpine
    container_name: minio-nginx
    volumes:
      - ./minio/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "3002:9000"
      - "3001:9001"
    depends_on:
      - minio
    restart: always
```

If I use console address, image will store as xl.meta
![image](https://user-images.githubusercontent.com/43648013/182829080-99569532-cf58-4e52-ac51-6da55400b38f.png)
In this way I can't retrieve images if occur any issue.
How can I still use console address but image should store actual image?

This is code example:
```js
var Minio = require('minio');

var minioClient = new Minio.Client({
  endPoint: ,
  port: ,
  useSSL: false,
  accessKey: '',
  secretKey: '',
});

// Make a bucket called photos.
minioClient.makeBucket('photos', 'us-east-1', function (err) {
  if (err) {
    console.log(err);
  } else {
    console.log('Bucket created successfully in "us-east-1".');
  }

  // Using fPutObject API upload your file to the bucket photos.
  minioClient.fPutObject('photos', 'test.jpg', 'C:\\Users\\USER\\Desktop\\testminio\\test.jpg', function (err, etag) {
    if (err) return console.log(err);
    console.log('File uploaded successfully.');
  });
});
 
```
