### ISSUE TITLE
auth with spring gateway

### ISSUE THREAD

**Issue by miniboxhaha** [minio/minio-js#1107]
i deploy minio behind spring gw
minio api server : 192.168.8.134:9500
minio console : 192.168.8.134:9501

here is my docker compose file
```
minio:
    image: bitnami/minio
    container_name: minio
    ports:
      - "9500:9000"
      - "9501:9001"
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=12345678
      - MINIO_DEFAULT_BUCKETS=my-bucket:public
```

here is my spring gateway config
```
server:
    port: 8000
    address: 0.0.0.0

spring:
  cloud:
    gateway:
       routes:
       - id: minio_api
         uri: http://192.168.8.134:9500
         predicates:
         - Path=/**
```

i use minio-js connect minio from browser (chrome)
```
new Minio.Client(
    {
        endPoint: "192.168.8.134",
        port: 9500,
        useSSL: false,
        accessKey: "root",
        secretKey: "12345678",
    }
)
```

when port set is 9500 , it works fine. but when i use 8000, request failed.

look into the request , the only different is authorization in headers.

i test in postman to requset **http://192.168.8.134:8000** but use authorization calc by port 9500. it works.

**Comment by prakashsvmx** [comment]
if proxy is used , the headers should be passed (host) for the correct calculation of S3v4. could you check. So it is not a sdk/minio issue
eg. nginx 
https://github.com/minio/minio/blob/master/docs/orchestration/docker-compose/nginx.conf

**Comment by miniboxhaha** [comment]
@prakashsvmx thanks for your advise
i change spring gateway config to this, and is works
```
server:
    port: 8000
    address: 0.0.0.0

spring:
  cloud:
    gateway:
       routes:
       - id: minio_api
         uri: http://192.168.8.134:9500
         predicates:
         - Path=/**
         filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_LAST
        - PreserveHostHeader
```
