### ISSUE TITLE
[BUG] cannot sql over file locally

### ISSUE THREAD

**Issue by omernach** [minio/minio-js#1172]
I'm running minio locally on docker and I have a json lines file.
Since it's all on my local machine I'm not using SSL.
When I run this CLI command everything works just fine:
```
 mc sql --query "select s.name from S3Object as s where s.name = '7PvHzw' limit 5" minio/testbucket/testObject.json 
 ```
 
 When I tried to convert it to my JS code I got this error:
 ```
 Error: Header Checksum Mismatch, Prelude CRC of 41 does not equal expected CRC of -6437716
 ```
 
 Here is my code:
 ```
 const Minio = require('minio');
 const minioClient = new Minio.Client({ accessKey: ACCESS_KEY, secretKey: SECRET_KEY, endPoint: 'localhost', port: 9000, useSSL: false });
 minioClient.selectObjectContent('testbucket', 'testObject.json', {
    expression: "select s.name from S3Object as s where s.name = '7PvHzw' limit 5",
    inputSerialization: { JSON: { Type: "LINES" } },
    outputSerialization: { JSON: { RecordDelimiter: "\n" } }, 
    expressionType: "SQL"
}).then(res => {
    console.log(res);
    console.log('Success')
}).catch(err => {
    if (err) {
        return console.log('Unable to process select object content.', err.message)
    }
});
```
About my machine: macbook with intel i7
Docker compose:
```
  minio:
    image: minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ~/minio_data:/data
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
    command: server --console-address ":9001" /data
```
