### ISSUE TITLE
Presigned URL from minio is not working

### ISSUE THREAD

**Issue by pforprince** [minio/minio-js#1203]
Hi there, I'm using Minio in project. Now, I want to keep the bucket private. I'm able to use the upload feature from my application but while getting preSignedUrl, I'm stuck. The URL it is returning it is not valid. Not showing the image as expected. But when I visit the console and share a file from there, it is working fine. Displaying the file as expected. I've provided both URLs in description. 

Things to notice => 
Apart from host in both URLs, there are some things different. 
Security Token is missing from my own generated URLs
Mine is using a different credentials value 

**Below are the code details.** 

Package.json 
```
 "minio": "^7.1.1"
```

Docker compose -  
```
  image-service:
    image: minio/minio
    container_name: image-service
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - marriage-rubru-tier      
    env_file: ./.env  
    volumes:
      - minio-vol:/data   
    restart: "unless-stopped"
    command: server --console-address ":9001" /data
```

Minio Client - 
```
var minioClient = new Minio.Client({
    // endPoint: '13.233.105.42',
    endPoint: 'image-service',
    port: 9000,
    useSSL: false,
    accessKey: MINIO_ACCESS_KEY,
    secretKey: MINIO_SECRET_KEY
});
```

Function to get URL - 
```
const getFileUrl = async (fileName, expiresIn = 60 * 60, bucketName = 'profiles') => {
    return await minioClient.presignedGetObject(bucketName, fileName, expiresIn);
}

```
Minio console URL 
```
http://127.0.0.1:9000/profiles/image-1693029523366-326398589.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=4L5XW1QG8FPQEZOTX3DC%2F20230826%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230826T070653Z&X-Amz-Expires=262800&X-Amz-Security-Token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiI0TDVYVzFRRzhGUFFFWk9UWDNEQyIsImV4cCI6MTY5MzA3MzI3NiwicGFyZW50IjoibWluaW8ifQ.yok4jcTtHLBmPT4cAzJcqKzCHpTapPp5nwy7FROKchHgkcS8PSwgzFs3SB8NU0KvSx_ZfNZ3Wa5y5-FDgbYG6Q&X-Amz-SignedHeaders=host&versionId=null&X-Amz-Signature=0a17eba6caa7ec65b2510b86747f26efae59e317878e81b95b1c3608c2502f5f
```

Url that I'm getting 
```
 http://image-service:9000/profiles/image-1693029523366-326398589.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20230826%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230826T070007Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=b48d584d98165171423d72d688f2525ab54353a6dc7105f1bd91074ca54788ab
 ```
