### ISSUE TITLE
`S3Error: Invalid Request (invalid hostname)` occurs when a Docker container has a valid hostname that includes an `_` underscore.

### ISSUE THREAD

**Issue by Trucker9** [minio/minio-js#1362]
Hi,

I tried to connect to the MinIO container that I deployed locally using the following configuration:
```
  minio_pishrun:
    image: minio/minio:latest
    container_name: minio_pishrun
    ports:
      - "9000:9000"
      - "9001:9001" 
    environment:
      MINIO_ROOT_USER: "something"
      MINIO_ROOT_PASSWORD: "something"
    command: server /data --console-address ":9001"
    volumes:
      - minio_pishrun_data:/data
```

I created a client instance as:
```
export const minioClient = new Minio.Client({
  // ...
  endPoint: 'minio_pishrun',
  // ...
});
```

However, I encountered the error `S3Error: Invalid Request (invalid hostname)` every time I tried to perform an operation.

After some research, I came across [a similar issue in the Python package](https://github.com/minio/minio-py/issues/760).) Following the solution mentioned there, I removed the underscore from the name and used `minoPishrun` instead, which resolved the issue.
