### ISSUE TITLE
Unable to connect to S2 storage with certificate

### ISSUE THREAD

**Issue by slim-hmidi** [minio/minio-js#826]
I'm trying to access the aws s3 using minio client, so I tried this simple example:
```
const MinioClient = require('minio').Client;

const client = new MinioClient({
  endPoint: "my_end_point",
  port: 4443,
  accessKey: "access_key",
  secretKey: "secret_key"
});

client.makeBucket('new-bucket-2020', 'eu-central-1', (err) => {
  if (err) console.log(err)
})
```
in my docker compose I added the certs folder which contains cert.pem (CA certificate) to volume:
```
services:
  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
      - ./certs:/certs
    ports:
      - '9001:9000'
    environment:
      MINIO_ACCESS_KEY: minio_access
      MINIO_SECRET_KEY: minio_secret
    command: minio server /data
```
However when I run my code I got this error:
```
{ Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket._finishInit (_tls_wrap.js:643:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }
```
and this error is due to certificate needed to connect to S3. How can I fix that?
