### ISSUE TITLE
Using MINIO with kubernetes ambassador returns InvalidEndpointError: Invalid endPoint : undefined

### ISSUE THREAD

**Issue by hamedminaee** [minio/minio-js#828]
I am having a frustrating issue. I use MINIO as a object storage platform. I have it deployed in Open shift and in my open shift I have ambassador for routing. So when I use the direct route using ocp I am able to generate pre signed url and create buckets... so everything is fine but as soon I use ambasador as follows:

```
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: _api_minio
      service: "http://minio-svc:9000"
      prefix: /api/minio/
      rewrite: /
      bypass_auth: true
      host: xxx.xxx.xxx.xxxx.com
      add_response_headers:
        Strict-Transport-Security: max-age=15552000; includeSubDomains
        X-Frame-Options: SAMEORIGIN
```

So using ocicp8.xxx.xxx.xxxx.com/api/minio instead of direct route using the following initialization 

```
var minioClient = new Minio.Client({
    endpoint: "xxx.xxx.xxx.xxx.com/minio",
    accessKey: 'xxxx',
    useSSL: false,
    secretKey: 'xxxxxx'
})

```
```
 give me the following error: 

node_modules/minio/dist/main/minio.js:90
      throw new errors.InvalidEndpointError(`Invalid endPoint : ${params.endPoint}`);
      ^
InvalidEndpointError: Invalid endPoint : undefined
```

But as soon as I use direct rouite everything works. Just to try out a different library I used IBM-cos and I got different issues but same result not working

https://github.com/IBM/ibm-cos-sdk-js/issues/59

Any help is appreciated
